# ===================================================
# Makefile for LaTeX 
# ===================================================

default: report

clean:
	cd LaTeX;make clean

report:
	cd LaTeX;make



